# Basic workflow from https://github.com/ruby/setup-ruby

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5 
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        HEADLESS=true bundle exec rspec spec/features 
