# Basic workflow from https://github.com/ruby/setup-ruby

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
       - uses: actions/checkout@v1

       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.6.5

       - name: Install dependent libraries
         run: sudo apt-get install libpq-dev

       - name: Bundle install
         run: |
           gem install bundler
           bundle install --jobs 4 --retry 3
       - name: setup databases
         env:
           POSTGRES_PASSWORD: postgres
           POSTGRES_USER: postgres
           RAILS_ENV: test
         run: bundle exec rake db:setup
       - name: run tests
         run: HEADLESS=true bundle exec rspec spec/features 
