# Basic workflow from https://github.com/ruby/setup-ruby

name: Test
on: [push, pull_request]
env:
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
       - uses: actions/checkout@v1
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.6.5
           bundler-cache: true
       - name: Install dependent libraries
         run: sudo apt-get install libpq-dev
       - name: Bundle install
         run: |
           gem install bundler
           bundle install --jobs 4 --retry 3
           bundle exec rails webpacker:install
       - name: Setup test database
         run: bundle exec rails db:create db:migrate
       - name: run tests
         run: HEADLESS=true bundle exec rspec spec/features 
