# Basic workflow from https://github.com/ruby/setup-ruby

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5 
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
    - run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        HEADLESS=true bundle exec rspec spec/features 
